### ISSUE TITLE
Update erases all data from the app!

### ISSUE THREAD

**Issue by braincleaner** [IngmarStein/Kraftstoff#1]
The update to version 1.2 erases all data from the app! I've lost data from 3 years.
How do I get this data back?

**Comment by mbharder** [comment]
Same problem with my data (nearly 4 years for 3 cars - needed for business). Opening after installation and all data was gone, no more vehicle registrated or shown, neither any fueldata. Fast correction needed!

**Comment by murdock007** [comment]
Same problem here. Lost 4J of data. Is there a solution? Would it be possible to geht the Data back from iCloud? According To my Settings it should  be  saved in the cloud.

**Comment by IngmarStein** [comment]
First of all: the data has not been deleted and is not lost. It's still stored on your device, version 1.2.1 (which I pulled from the store) is just unable to access it. The problem is the result of a bugfix: version 1.2 had iCloud support without the proper entitlement for iCloud Documents. I've added that entitlement in 1.2.1 but it's almost impossible to test locally as App Store release versions behave differently than development versions.
I've used one of my two Developer Technical Support (DTS) incidents to contact Apple. Here's what I asked, in case anyone knows the answer already:

-----------

PLATFORM AND VERSION
iOS
iOS 8.4

DESCRIPTION OF PROBLEM
I'm facing a data migration issue when I wanted to enable iCloud syncing for my Core Data based app.

Up until version 1.1, I haven't used iCloud at all and used a local Core Data store.
In version 1.2, I've enabled iCloud key-value storage and a migration step to migrate the local store to one with a NSPersistentStoreUbiquitousContentNameKey. However, I forgot to also enable iCloud Documents.
In version 1.2.1, I've enabled iCloud Documents, but all my users now seem to have a new, empty store. I've seen that during testing, but I thought this was because I was upgrading a release version with a development version (https://developer.apple.com/library/ios/qa/qa1883/_index.html).

Looking at the app container, the stores were in the following locations:

1.1: Documents/Krafstoff.sqlite
1.2: Documents/CoreDataUbiquitySupport/mobile~…/Kraftstoff/local/store/Fuel.sqlite
1.2.1: Documents/CoreDataUbiquitySupport/mobile~…/Kraftstoff/<UUID>/store/Fuel.sqlite

The problem seems to be that when I enable iCloud Documents, the "local" folder is ignored (and not automatically used for an initial sync, as I had hoped). Is there a way to access the store in "local", so that I can push an update which imports all the data from there to the new location?
When I try to use the store at the "local" location with a manually constructed URL, addPersistentStoreWithType fails with the message "Looks like we were passed the full URL, not the store file URL".

My project is open source and all the Core Data related code is here:
https://github.com/IngmarStein/Kraftstoff/blob/master/Classes/CoreDataManager.swift

STEPS TO REPRODUCE
1) Create an app and enable iCloud key-value storage
2) Create a store with a NSPersistentStoreUbiquitousContentNameKey and save some data
3) Enable iCloud Documents
4) Load the same store (same URL and options) and find that the store is empty

APP NAME AND ID IN APP STORE
Kraftstoff
471634654

**Comment by murdock007** [comment]
Thank for clarifying the problem but we need a solution. If the new version 1.2.1 does not work and the data is still stored on the device, would it be possible to issue a  patch to go back to a working version of the app?

**Comment by IngmarStein** [comment]
Version 1.2.2 which hopefully fixes the problem is already waiting for review by Apple.

**Comment by zacc1** [comment]
I installed version 1.2.2 today, but the problem seems not to be solved, my data is still gone. Tried also a reboot. iPhone 6 & iOS 8.4.1. Is there any possibility to get the data back?

**Comment by mbharder** [comment]
same situation like zacc1 - quick solution needed!

**Comment by murdock007** [comment]
Same here, version 1.2.2 does not solve the problem.

**Comment by IngmarStein** [comment]
The project is open source, feel free to submit patches :)

Can anyone check which files are in the Documents folder (using iFile, iExplorer or something similar)?
The app is currently looking at the following to places to migrate old data:
- Documents/Kraftstoff.sqlite (-wal) (Data from versions before 1.2)
- Documents/CoreDataUbiquitySupport/mobile~…/Kraftstoff/local/store/Fuel.sqlite (Data from version 1.2)

The new location is
Documents/CoreDataUbiquitySupport/mobile~…/Kraftstoff/_UUID_/store/Fuel2.sqlite

**Comment by mbharder** [comment]
![system](https://cloud.githubusercontent.com/assets/13998616/9680211/7a7ac53e-52f5-11e5-9c08-6b3153e62d63.jpg)
Cannot find the mentioned folders - watch jpg...

**Comment by zacc1** [comment]
I would like to help...but is there a possibility to check the mentioned folders without having a jailbreak? And if yes, which tool do I have to use?

**Comment by mbharder** [comment]
![screenshot](https://cloud.githubusercontent.com/assets/13998616/9682895/3192e728-530b-11e5-846d-72e2705bd867.jpg)
@IngmarStein 
Here another Screenshot, directly from the phone - Folder "Documents" - there is no data file or folder to find you mentioned in your last comment (app used for shot "iexplore file manager")

**Comment by IngmarStein** [comment]
I wasn't talking about /var/mobile/Documents, but the Documents folder inside of the app container.

**Comment by mbharder** [comment]
sorry, i'm just a user, not a programmer and wanted to help... How can i find it?

**Comment by IngmarStein** [comment]
Another user just tweeted that his cars (along with all the data) reappeared in 1.2.2 when he tried to enter new fill-up.

**Comment by mbharder** [comment]
fill-up entered but no cars...

**Comment by zacc1** [comment]
I tried it too....new fill-up entered, but data still gone, no cars... :-(

**Comment by murdock007** [comment]
Tried to enter fill-up as well. It did not work.

**Comment by trumpar** [comment]
I tried also to fill-up, but no data reapear...
But I used iexplorer to read out the sql-data. That worked. The data seams to be completely stored in the db.
Is there a way to put the exported sql-tables back in the app?

**Comment by IngmarStein** [comment]
In which location did you find the sqlite data? Was it named Kraftstoffrechner.sqlite or Fuel.sqlite?

**Comment by trumpar** [comment]
The data was locatet at
1) AppDomain-com.github.m-schmidt.kraftstoff\Documents
2) AppDomain-com.github.m-schmidt.kraftstoff\Documents\CoreDataUbiquitySupport\mobile~[ID2]\Kraftstoff\local\store\Fuel.sqlite

no data could be found at:
1) AppDomain-com.github.m-schmidt.kraftstoff\Documents\CoreDataUbiquitySupport\mobile~[ID1]\Kraftstoff\[IDx]\store\Fuel.sqlite
2) AppDomain-com.github.m-schmidt.kraftstoff\Documents\CoreDataUbiquitySupport\mobile~[ID1]\Kraftstoff2\[IDy]\store\Fuel.sqlite

**Comment by IngmarStein** [comment]
Aha, so there are now two different peers (ID1 and ID2 in your example), this is why the following code to locate the old store fails:
```
private static var iCloudLocalStoreURL : NSURL? {
		let ubiquityContainer = NSURL(fileURLWithPath:applicationDocumentsDirectory)!.URLByAppendingPathComponent("CoreDataUbiquitySupport")
		var error : NSError?
		if let peers = NSFileManager.defaultManager().contentsOfDirectoryAtURL(ubiquityContainer, includingPropertiesForKeys: nil, options: .allZeros, error: &error) where peers.count == 1 {
			if let peer = peers.first as? NSURL {
				return peer.URLByAppendingPathComponent("Kraftstoff/local/store/Fuel.sqlite")
			}
		}
		return nil
	}
```
I'll try to figure out a way to import that data in the next update, while still keeping the data entered with 1.2.2

**Comment by zacc1** [comment]
Hello IngmarStein, thanks in advance for finding a solution, it would be great to get the data back. If I would be a programmer I would support. How long do you think it'll take you to create the update that brings the data back? Thanks again, zacc1

**Comment by IngmarStein** [comment]
I just submitted 1.2.3 to the App Store. Usually, it takes ~1 week until the update is approved.

**Comment by IngmarStein** [comment]
1.2.3 is out. Does it it bring back your old data?

**Comment by mbharder** [comment]
Data now is visible - Thanks for fixing the problem!

**Comment by IngmarStein** [comment]
I'm glad to hear that. Please leave a positive review, if you're satisfied :-)

**Comment by zacc1** [comment]
Same as mbharder: my data is back, thx a lot!

**Comment by mbharder** [comment]
I will do so!

**Comment by trumpar** [comment]
My Data is also back. Thanks a lot for your rapid fix!

**Comment by Christophs007** [comment]
The data with the new update 1.2.3 wasn't not in the Kraftstoff-app.

**Comment by Christophs007** [comment]
iCloud:
![bildschirmfoto 2015-09-16 um 19 57 57](https://cloud.githubusercontent.com/assets/14317846/9913624/19f87ac2-5cae-11e5-8f7d-463fddf6017e.png)

**Comment by Christophs007** [comment]
Backup:
![bildschirmfoto 2015-09-16 um 20 00 29](https://cloud.githubusercontent.com/assets/14317846/9913728/89006d4e-5cae-11e5-953c-533c3ee1955d.png)

**Comment by Christophs007** [comment]
I have clean the app "kraftstoff" in the first days of September. And install with the itunes on my mac an old version (from my backup-hard disk) but the datas are not back in my app :-(

Can you help me, please?

**Comment by murdock007** [comment]
Have a similar problem as Christophs007. After the update to the faulty version 1.2.1 I uninstalled and re installed the app hoping to get the data back from iCloud. But it failed....  Now with the new version 1.2.3 still no data visible. I am really disappointed and have lost 4j of data

**Comment by IngmarStein** [comment]
It was actually version 1.2 which had the bug (iCloud was enabled but not iCloud Documents), that just became visible when 1.2.1 was published with iCloud Documents. When you uninstalled the app from the device, you've deleted all your local data. The only way to get it back, is to retrieve it from a backup.

**Comment by murdock007** [comment]
Thank you  for replying. As far as I understood it it is not possible to selectively restore data from a single app from a backup. My last backup is more than 6 month old and I would loose all the data I have entered in 5 other apps. So this solution will just not work for me.

**Comment by IngmarStein** [comment]
In case you have never exported your data as CSV files, you can try to browse your iTunes backup with a tool such as iExplorer (https://www.macroplant.com/iexplorer/tutorials/how-to-browse-backups-on-iphone) or iBackup Viewer (http://www.imactools.com/iphonebackupviewer/).

**Comment by CaparsoX** [comment]
My data was also back with the update to 1.2.3 but then I updated to iOS 9 and enabled iCloud Drive and now it's lost again. Don't know whether it's related to iOS 9 or iCloud Drive as I haven't used the app after updating to iOS 9 and before enabling iCloud Drive.

I used iBackup Viewer to look for the data and found several sqlite-files. This seems somewhat similar to what trumpar posted back on Sep. 7.

com.github.m-schmidt.kraftstoff\Documents\Kraftstoffrechner.sqlite.migrated
com.github.m-schmidt.kraftstoff\Documents\Kraftstoffrechner.sqlite-shm
com.github.m-schmidt.kraftstoff\Documents\Kraftstoffrechner.sqlite-wal (This seems to be the one with all my data as it's 194 KB and all other files are only between 32 and 64 KB. After opening the file with Notepad I also found a reference about my car and the license plate I entered when creating it.)

com.github.m-schmidt.kraftstoff\Documents\CoreDataUbiquitySupport\mobile~[ID1]\Kraftstoff2\[IDx]\store\Fuel.sqlite
com.github.m-schmidt.kraftstoff\Documents\CoreDataUbiquitySupport\mobile~[ID1]\Kraftstoff2\[IDy]\store\Fuel.sqlite (Also includes a reference about my car.)
com.github.m-schmidt.kraftstoff\Documents\CoreDataUbiquitySupport\mobile~[ID1]\Kraftstoff2\local\store\Fuel.sqlite

com.github.m-schmidt.kraftstoff\Documents\CoreDataUbiquitySupport\mobile~[ID2]\Kraftstoff\local\store\Fuel.sqlite.migrated (Also includes a reference about my car.)

Is there a way to fix this? Is it possible to export the sqlite-data and import it in the app? Or can you fix it with another app update? Really appreciate your help.
